In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\piyul\\Desktop\\kaggle\\Latest_file.csv")
df.head()

C:\Users\piyul\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   BASELINE_PRICE EFFECTIVE_DATE      PART_NUMBER  Count  SAP_SITE_ID
0             0.0       3-Jan-19     613-1340-001    1.0       1095.0
1             0.0       3-Jan-19     434-0015-013    1.0       1095.0
2             0.0       3-Jan-19  HS0-508BRH-Q//G    1.0       1095.0
3             0.0       3-Jan-19     440-1172-001    3.0       1095.0
4             0.0       3-Jan-19     150-5003-069    1.0       1095.0

In [2]:
df=df.dropna()
df.tail()

       BASELINE_PRICE EFFECTIVE_DATE      PART_NUMBER  Count  SAP_SITE_ID
82214       181750.00       1-Jan-19     56008944-301    2.0       1045.0
82215       195632.27       2-Jan-19     22010120-005    2.0       1065.0
82216       195632.27       1-Jan-19     22010120-005    2.0       1065.0
82217       246099.33       2-Jan-19  22010120-001//U    2.0       1065.0
82218       246099.33       1-Jan-19  22010120-001//U    2.0       1065.0

In [3]:
df['EFFECTIVE_DATE'] = pd.to_datetime(df['EFFECTIVE_DATE'])

In [4]:
df.to_csv("C:\\Users\\piyul\\Desktop\\kaggle\\filtered_dataset.csv")

In [5]:
col=["base_price","date","part_num","count","sap_id"]

In [6]:
df= pd.read_csv("C:\\Users\\piyul\\Desktop\\kaggle\\filtered_dataset.csv",names=col,header=0)
df.head()

   base_price        date         part_num  count  sap_id
0         0.0  2019-01-03     613-1340-001    1.0  1095.0
1         0.0  2019-01-03     434-0015-013    1.0  1095.0
2         0.0  2019-01-03  HS0-508BRH-Q//G    1.0  1095.0
3         0.0  2019-01-03     440-1172-001    3.0  1095.0
4         0.0  2019-01-03     150-5003-069    1.0  1095.0

In [7]:
df["num_id"] = df["part_num"] + " _ " + df["sap_id"].map(str)

In [8]:
df=df.drop(["part_num","sap_id"],axis=1)

In [9]:
df.shape

(82219, 4)

In [10]:
df=df.groupby('num_id').head(1)
df

        base_price        date  count                      num_id
0           0.0000  2019-01-03    1.0       613-1340-001 _ 1095.0
1           0.0000  2019-01-03    1.0       434-0015-013 _ 1095.0
2           0.0000  2019-01-03    1.0    HS0-508BRH-Q//G _ 1095.0
3           0.0000  2019-01-03    3.0       440-1172-001 _ 1095.0
4           0.0000  2019-01-03    1.0       150-5003-069 _ 1095.0
5           0.0000  2019-01-03    1.0       652-0359-001 _ 1095.0
6           0.0000  2019-01-03    1.0       652-0359-002 _ 1095.0
7           0.0000  2019-01-03    1.0       653-8034-003 _ 1095.0
8           0.0000  2019-01-03    1.0       654-8230-002 _ 1095.0
9           0.0000  2019-01-03    1.0       151-5033-511 _ 1095.0
10          0.0000  2019-01-03    1.0       320-0001-015 _ 1095.0
11          0.0000  2019-01-03    1.0       509-2005-009 _ 1095.0
12          0.0000  2019-01-03    2.0       68010653-001 _ 1095.0
13          0.0000  2019-01-03    1.0       322-0919-001 _ 1095.0
14          0.0000  2019-01-03    1.0       520-0004-012 _ 1095.0
15          0.0000  2019-01-03    1.0       530-0072-001 _ 1095.0
16          0.0000  2019-01-03    3.0       530-0503-001 _ 1095.0
17          0.0000  2019-01-03    3.0       531-0059-001 _ 1095.0
18          0.0000  2019-01-03    3.0          702-14937 _ 1095.0
19          0.0000  2019-01-03    1.0   MS3116F16-26P//G _ 1095.0
20          0.0000  2019-01-03    1.0   MS3116F16-26S//G _ 1095.0
21          0.0000  2019-01-03    1.0          558-4105G _ 1095.0
22          0.0000  2019-01-03    3.0           558-4108 _ 1095.0
23          0.0000  2019-01-03    1.0    75000367-001//G _ 1095.0
24          0.0000  2019-01-03    3.0    75000369-001//G _ 1095.0
25          0.0000  2019-01-03    3.0    75000372-001//G _ 1095.0
26          0.0000  2019-01-03    3.0    75000374-001//G _ 1095.0
27          0.0000  2019-01-03    3.0    75000379-001//G _ 1095.0
28          0.0000  2019-01-03    1.0    75001386-001//G _ 1095.0
29          0.0000  2019-01-03    1.0    75001418-001//G _ 1095.0
...            ...         ...    ...                         ...
82160   73475.1613  2019-01-02    2.0          2819232-2 _ 1008.0
82162   78400.0000  2019-01-02    2.0      34200650-Y004 _ 1045.0
82164   80122.5100  2019-01-02    2.0        7023173-902 _ 5010.0
82166   80440.0000  2019-01-02    2.0          HG9740FG2 _ 3202.0
82168   80926.6800  2019-01-02    2.0     066-50008-0408 _ 5010.0
82170   81300.0000  2019-01-02    2.0  34200650-WB6R-001 _ 1045.0
82172   82500.0000  2019-01-02    2.0      34200650-WYX2 _ 1045.0
82174   93107.5800  2019-01-02    2.0    22010120-002//U _ 1065.0
82176  100000.0000  2019-01-02    2.0         7516118-27 _ 5210.0
82177  100000.0000  2019-01-02    2.0         7516118-77 _ 5210.0
82180  100000.0000  2019-01-02    2.0       56008928-301 _ 1045.0
82182  104271.0000  2019-01-02    2.0       64008653-901 _ 1006.0
82183  104271.0000  2019-01-02    2.0       64007719-902 _ 1006.0
82186  109962.1025  2019-01-02    2.0      7516118-27130 _ 1103.0
82188  118765.0000  2019-01-02    2.0       73004079-001 _ 1039.0
82190  124214.8900  2019-01-02    2.0    22011033-002//U _ 1065.0
82192  140956.7400  2019-01-02    2.0      7516118-77145 _ 1103.0
82193  140956.7400  2019-01-02    2.0      7516118-77135 _ 1103.0
82196  144011.0000  2019-01-02    2.0       26015086-104 _ 1062.0
82198  145737.1700  2019-01-02    2.0    22010120-004//U _ 1065.0
82200  150829.4600  2019-01-01    1.0      7516118-47145 _ 5210.0
82201  154018.6200  2019-01-02    2.0      7516118-27010 _ 5253.0
82203  154086.5000  2019-01-02    2.0       26015086-103 _ 1062.0
82205  155567.3700  2019-01-02    2.0      7516118-27011 _ 1103.0
82207  155574.3600  2019-01-02    2.0      7516118-27010 _ 1103.0
82209  156707.1000  2019-01-02    2.0       22011033-003 _ 1065.0
82211  166274.8300  2019-01-02    2.0        4052508-960 _ 5010.0
82213  181750.0000  2019-01-02    2.0       56008944-301 _ 1045.0
82215  195632.2700  2019-01-02    2.0       22010120-005 _ 1065.0
82217  246099.3300  2019-01-02    2.0    22010120-001//U _ 1065.0

[42462 rows x 4 columns]

In [12]:
df.shape

(42462, 4)

In [11]:
df['date'] = pd.to_datetime(df['date'])

In [12]:
df = df.sort_values(by='date',ascending=True)
df

       base_price       date  count                      num_id
60347    121.9208 2019-01-01    2.0          8531178-1 _ 1073.0
77218   2074.4800 2019-01-01    2.0    10147526-101SUB _ 1064.0
44441     21.7183 2019-01-01    2.0          4073796-7 _ 5210.0
77234   2080.6820 2019-01-01    2.0          91-0807-1 _ 1600.0
77237   2082.2300 2019-01-01    1.0       722-4223-013 _ 5253.0
77263   2091.8340 2019-01-01    1.0       34209277-005 _ 1039.0
56193     75.0000 2019-01-01    1.0           04003310 _ 1006.0
64656    219.5944 2019-01-01    2.0        7519272-901 _ 1103.0
77306   2116.4629 2019-01-01    2.0   7036319-1905//CM _ 5210.0
77310   2118.7500 2019-01-01    1.0  34209400-TB44-001 _ 1039.0
64643    219.3600 2019-01-01    1.0        7022141-804 _ 5210.0
56230     75.1536 2019-01-01    2.0       704-2830-002 _ 1095.0
77212   2072.8706 2019-01-01    2.0        7516129-913 _ 1009.0
77337   2137.7029 2019-01-01    2.0         73000146-9 _ 1073.0
77356   2148.6400 2019-01-01    1.0          2815262-2 _ 1008.0
14944      0.4731 2019-01-01    2.0     025-00004-0006 _ 5210.0
77369   2155.5704 2019-01-01    2.0   4089470-1005//CM _ 5210.0
77419   2189.5225 2019-01-01    2.0      60001090-1002 _ 5210.0
64535    215.0487 2019-01-01    2.0       34211391-006 _ 1039.0
44244     21.3247 2019-01-01    2.0         53003998-1 _ 5210.0
77440   2200.0000 2019-01-01    1.0          FG220A272 _ 1062.0
77441   2200.0000 2019-01-01    1.0          FG220A280 _ 1062.0
77442   2200.0000 2019-01-01    1.0           FG250A47 _ 1062.0
77453   2207.2214 2019-01-01    2.0   4093332-1003//CM _ 5210.0
77462   2214.9224 2019-01-01    2.0        7510114-855 _ 1103.0
77340   2137.8700 2019-01-01    1.0       7036319-1905 _ 5210.0
56354     76.2294 2019-01-01    2.0         53000607-1 _ 5210.0
77209   2070.6257 2019-01-01    2.0       7034056-1901 _ 1103.0
35343      7.8844 2019-01-01    2.0            A4513-1 _ 1600.0
77039   1989.7647 2019-01-01    1.0  360-0101-002__CAR _ 1009.0
...           ...        ...    ...                         ...
1946       0.0000 2019-01-03    1.0         8521877-15 _ 1039.0
1945       0.0000 2019-01-03    1.0         8521874-29 _ 1039.0
1944       0.0000 2019-01-03    1.0         8521873-73 _ 1039.0
1987       0.0000 2019-01-03    1.0        53500022-22 _ 1039.0
1964       0.0000 2019-01-03    1.0         53000237-2 _ 1039.0
1963       0.0000 2019-01-03    1.0         53000236-1 _ 1039.0
1966       0.0000 2019-01-03    1.0    M55342K06B301DR _ 1039.0
1985       0.0000 2019-01-03    1.0         53001994-1 _ 1039.0
1984       0.0000 2019-01-03    1.0         53001595-1 _ 1039.0
1983       0.0000 2019-01-03    1.0    M39014/01-1311V _ 1039.0
1982       0.0000 2019-01-03    1.0     M39006/25-0217 _ 1039.0
1981       0.0000 2019-01-03    1.0    M55342E06B5E11R _ 1039.0
1980       0.0000 2019-01-03    1.0       68001712-102 _ 1039.0
1979       0.0000 2019-01-03    1.0  500T010A37F09//TE _ 1039.0
1978       0.0000 2019-01-03    1.0     22255C105KAT2A _ 1039.0
1977       0.0000 2019-01-03    1.0    M55342K06B249ER _ 1039.0
1976       0.0000 2019-01-03    1.0    M55342K06B1B60R _ 1039.0
1975       0.0000 2019-01-03    1.0    M55342K06B12E4R _ 1039.0
1974       0.0000 2019-01-03    1.0    M55342K02B7B50P _ 1039.0
1973       0.0000 2019-01-03    1.0    M55342K02B49D9R _ 1039.0
1972       0.0000 2019-01-03    1.0    M55342K02B100DR _ 1039.0
1971       0.0000 2019-01-03    1.0    M55342E11B6B98R _ 1039.0
1970       0.0000 2019-01-03    1.0    M55342E11B1B00R _ 1039.0
1969       0.0000 2019-01-03    1.0    M55342E11B10B0R _ 1039.0
1968       0.0000 2019-01-03    1.0          04051-017 _ 1039.0
1967       0.0000 2019-01-03    1.0    M55342K06B40E2R _ 1039.0
1965       0.0000 2019-01-03    1.0    M55342K06B274ER _ 1039.0
0          0.0000 2019-01-03    1.0       613-1340-001 _ 1095.0
79883   4805.8200 2019-02-07    2.0      60000892-1902 _ 5210.0
80723   7410.4800 2019-03-01    1.0     940-000175-210 _ 1103.0

[42462 rows x 4 columns]

In [30]:
# df.sort_values("date", axis = 1, ascending = True, 
#                  inplace = True) 

# df.groupby(df['date'].dt.strftime('%B'))['num_id'].sort_values()

In [13]:
df.set_index('date', drop=True, append=False, inplace=True, verify_integrity=False)
df = df.sort_index()

In [14]:
df=df.groupby('num_id').head(1)
df

            base_price  count                      num_id
date
2019-01-01    121.9208    2.0          8531178-1 _ 1073.0
2019-01-01   2074.4800    2.0    10147526-101SUB _ 1064.0
2019-01-01     21.7183    2.0          4073796-7 _ 5210.0
2019-01-01   2080.6820    2.0          91-0807-1 _ 1600.0
2019-01-01   2082.2300    1.0       722-4223-013 _ 5253.0
2019-01-01   2091.8340    1.0       34209277-005 _ 1039.0
2019-01-01     75.0000    1.0           04003310 _ 1006.0
2019-01-01    219.5944    2.0        7519272-901 _ 1103.0
2019-01-01   2116.4629    2.0   7036319-1905//CM _ 5210.0
2019-01-01   2118.7500    1.0  34209400-TB44-001 _ 1039.0
2019-01-01    219.3600    1.0        7022141-804 _ 5210.0
2019-01-01     75.1536    2.0       704-2830-002 _ 1095.0
2019-01-01   2072.8706    2.0        7516129-913 _ 1009.0
2019-01-01   2137.7029    2.0         73000146-9 _ 1073.0
2019-01-01   2148.6400    1.0          2815262-2 _ 1008.0
2019-01-01      0.4731    2.0     025-00004-0006 _ 5210.0
2019-01-01   2155.5704    2.0   4089470-1005//CM _ 5210.0
2019-01-01   2189.5225    2.0      60001090-1002 _ 5210.0
2019-01-01    215.0487    2.0       34211391-006 _ 1039.0
2019-01-01     21.3247    2.0         53003998-1 _ 5210.0
2019-01-01   2200.0000    1.0          FG220A272 _ 1062.0
2019-01-01   2200.0000    1.0          FG220A280 _ 1062.0
2019-01-01   2200.0000    1.0           FG250A47 _ 1062.0
2019-01-01   2207.2214    2.0   4093332-1003//CM _ 5210.0
2019-01-01   2214.9224    2.0        7510114-855 _ 1103.0
2019-01-01   2137.8700    1.0       7036319-1905 _ 5210.0
2019-01-01     76.2294    2.0         53000607-1 _ 5210.0
2019-01-01   2070.6257    2.0       7034056-1901 _ 1103.0
2019-01-01      7.8844    2.0            A4513-1 _ 1600.0
2019-01-01   1989.7647    1.0  360-0101-002__CAR _ 1009.0
...                ...    ...                         ...
2019-01-03      0.0000    1.0         8521877-15 _ 1039.0
2019-01-03      0.0000    1.0         8521874-29 _ 1039.0
2019-01-03      0.0000    1.0         8521873-73 _ 1039.0
2019-01-03      0.0000    1.0        53500022-22 _ 1039.0
2019-01-03      0.0000    1.0         53000237-2 _ 1039.0
2019-01-03      0.0000    1.0         53000236-1 _ 1039.0
2019-01-03      0.0000    1.0    M55342K06B301DR _ 1039.0
2019-01-03      0.0000    1.0         53001994-1 _ 1039.0
2019-01-03      0.0000    1.0         53001595-1 _ 1039.0
2019-01-03      0.0000    1.0    M39014/01-1311V _ 1039.0
2019-01-03      0.0000    1.0     M39006/25-0217 _ 1039.0
2019-01-03      0.0000    1.0    M55342E06B5E11R _ 1039.0
2019-01-03      0.0000    1.0       68001712-102 _ 1039.0
2019-01-03      0.0000    1.0  500T010A37F09//TE _ 1039.0
2019-01-03      0.0000    1.0     22255C105KAT2A _ 1039.0
2019-01-03      0.0000    1.0    M55342K06B249ER _ 1039.0
2019-01-03      0.0000    1.0    M55342K06B1B60R _ 1039.0
2019-01-03      0.0000    1.0    M55342K06B12E4R _ 1039.0
2019-01-03      0.0000    1.0    M55342K02B7B50P _ 1039.0
2019-01-03      0.0000    1.0    M55342K02B49D9R _ 1039.0
2019-01-03      0.0000    1.0    M55342K02B100DR _ 1039.0
2019-01-03      0.0000    1.0    M55342E11B6B98R _ 1039.0
2019-01-03      0.0000    1.0    M55342E11B1B00R _ 1039.0
2019-01-03      0.0000    1.0    M55342E11B10B0R _ 1039.0
2019-01-03      0.0000    1.0          04051-017 _ 1039.0
2019-01-03      0.0000    1.0    M55342K06B40E2R _ 1039.0
2019-01-03      0.0000    1.0    M55342K06B274ER _ 1039.0
2019-01-03      0.0000    1.0       613-1340-001 _ 1095.0
2019-02-07   4805.8200    2.0      60000892-1902 _ 5210.0
2019-03-01   7410.4800    1.0     940-000175-210 _ 1103.0

[42462 rows x 3 columns]

In [15]:
df.to_csv("C:\\Users\\piyul\\Desktop\\kaggle\\filtered_dataset_5.csv")